services:
  # Backend Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mini-wolverine-backend-dev
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - LOG_LEVEL=info
      - CAITLYN_WS_URL=wss://116.wolverine-box.com/tm
      - CAITLYN_TOKEN=${CAITLYN_TOKEN}
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
      - /app/node_modules
    restart: unless-stopped
    
  # React Development Server
  react-app:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile.dev
    container_name: mini-wolverine-react-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_WS_URL=ws://localhost:4000
    volumes:
      - ./frontend-react/src:/app/src
      - ./frontend-react/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped